### ISSUE TITLE
Booleans always return true

### ISSUE THREAD

**Issue by rossanmol** [zoomsphere/ngx-store#1]
Hi,

Just tried using this, however when setting a boolean, the boolean will always return true even though the field is set to false in localStorage

**Comment by DanielKucal** [comment]
Hi @rossanmol, can you please provide more details about it like were you using Angular Service or Decorator? What version of `ngx-store` do you have installed? It'd be great if you could show me the code you were using. I have checked `@LocalStorage()` Decorator with initial value `false` and then set to false again and it works as expected... Thanks in advance for cooperation!

**Comment by DanielKucal** [comment]
I have located this issue. It was about not refreshing proxy object when setting primitive false-able values like `false`, `0`, `''`, `null` etc. It should be resolved in `v1.0.4`. 
Feel free to reopen if the problem still occurs.
