### ISSUE TITLE
WebStorables that implement an interface

### ISSUE THREAD

**Issue by BernhardBehrendt** [zoomsphere/ngx-store#10]
I've just migrated from the older repository to here and facing problems around interfaces in combination with Webstorables

    // Interface
    export interface Assistance {
        fat: number;
        carbs: number;
        protein: number;
    } 

    // Service
    type WebStorableSignature = Webstorable & Array<Assistance>;

    // also tried it with WebstorableArray
    type WebStorableSignature = WebstorableArray<Assistance>;

    @LocalStorage() public assistance: WebStorableSignature = <WebStorableSignature>[];

When I wan't to run the Code in the Browser (build is successful without warnings nor errors)
I'll run into a 

    AppComponent.html:1 ERROR RangeError: Maximum call stack size exceeded

I mostly guess it's a configuration fault by myself but maybe you can help me finding a indicator what to modify here.

**Addition**
I've checked the installed version on my running instance (server) where the latest app version runs.
There I have version https://github.com/zoomsphere/angular2-localstorage#v0.5.0 installed.

**Comment by DanielKucal** [comment]
Hi @BernhardBezdek, are you sure there is not installed more than one localstorage library in your project (please check `/node_modules`)? The error you're getting is not related to interfaces - can you show more of the code? I'd need to know what happens next with the decorated variable to help you.
It'd be great if you could also enable `debugMode` and paste uncollapsed logs for relevant items.

**Comment by DanielKucal** [comment]
Closing as outdated and invalid.
