### ISSUE TITLE
dependency on ts-debug, but ts-debug has no license

### ISSUE THREAD

**Issue by igoodrich** [zoomsphere/ngx-store#100]
Hi.  You guys have a dependency on ts-debug but that project does not have any license at all.  I filed an issue with ts-debug, but it may not be actively maintained.  Can anything be done about this?  Thank you.

**Comment by DanielKucal** [comment]
https://github.com/DanielKucal/ts-debug/blob/master/LICENSE.md
Added MIT license for ts-debug.
