### ISSUE TITLE
Feature suggestions: Support memory only cache

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/ngx-store#12]
I might be missing something but I can't see in the documentation a type of storage that will be cleaned when refreshing the browser.
The usage I need this for is for a component that is being created every time you open it and I want to store the data in between (this component has a search input and I want to store its state, related to #11).

AngularJs has `$cache` which doesn't exists anymore in Angular 2 and on.
Since this seems like an excellent fit to this library I would suggest adding it.

**Comment by DanielKucal** [comment]
`@SharedStorage()` decorator and `SharedStorageService` are exactly what you are looking for! :D

**Comment by HarelM** [comment]
I hoped this was it, the documentation in the readme file is pointing to a location that is not helpful though:
>Injectable LocalStorageService, SessionStorageService, CookiesStorageService and SharedStorageService (read more here)

further reading into the example shows a small comment that tell that, but I was not able to find it at first look.
>@SharedStorage() public title: string = 'Homepage'; // it will be kept in temp memory until app reload

Also the name is counter intuitive in my point of view, shared feels like something you can share between browsers or something (not that it's possible but hey maybe you cracked the system :-))

**Comment by DanielKucal** [comment]
Actually you are right, the name could be better. I was also considering `@TemporaryStorage()` and `@CacheStorage()`, but I came to the conclusion that the first is a bit too long and the second also is not more intuitive than `@SharedStorage()`... As the decorated variable isn't saved anywhere for longer, the only purpose of its decorator is to share the variable between components / services, so `@SharedStorage` didn't look like a bad idea... Of course I would like to hear some better names if you have some propositions :)

**Comment by HarelM** [comment]
Well, I don't think TemporaryStorage is too long, but you can always use TempStorage.
Other names that I can think of... well... 
VoletileStorage
RuntimeStorage
(In)MemoryStorage

**Comment by DanielKucal** [comment]
`@TempStorage()` is probably worth to consider. I will think about it, maybe make some poll, so everyone could give a vote. Anyway, you can use `@SharedStorage()` for now as it will be kept for some time and when new name appears the current one will be set as deprecated before removed, so everyone will can update his code.

**Comment by DanielKucal** [comment]
Aliases of shared storage i.e. `@TempStorage()` and `TempStorageService` have been introduced in v.1.4
