### ISSUE TITLE
Property default value overrides the stored value

### ISSUE THREAD

**Issue by KurtGokhan** [zoomsphere/ngx-store#13]
When a default value is defined for a property, that default value is written into the storage in object initialization. This only happens when the class is initialized for the second time without refreshing the page.

Assigning null, undefined or assigning in the constructor also reproduces the problem.

For example, go to the home component. The first value will be '1'. Change the value to '2' (I do it in developer tools). Refresh the page and you will see '2'. But navigate to another page and come back to the home page without refreshing. You will see the value has changed to '1'.

```
export class HomeComponent {
  @LocalStorage() public value: string = '1';
} 
```

I think package versions might be relevant. I am using Angular 4.3.2 and Typescript 2.4.2.

**Comment by DanielKucal** [comment]
Thanks for your report! Should be fixed in `v1.1.6`. Let me know if some problem still occurs, thanks.

Update: In `AoT` we need `ngOnDestroy()` method to be defined in class containing decorated property.
