### ISSUE TITLE
Unable to import WebStorageModule in AppModule

### ISSUE THREAD

**Issue by randychampagne** [zoomsphere/ngx-store#14]
Hello,

I am unable to import WebStorageModule in AppModule. I receive this non-descript error while compiling TypeScript:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

It seems to me that `WebStorageModule` isn't compatible with the latest version of NG2 but I may be missing something obvious. 

Here is a [link to the project on GH](https://github.com/yummy-bazaar/yummybazaar). Please try compiling it and let me know: 
1. Are you able to replicate the issue on your system?
2. What workaround do you suggest?

Cheers,

R

**Comment by DanielKucal** [comment]
Hey @champagne-randy, have you solved this issue?

**Comment by DanielKucal** [comment]
Closing as outdated.
