### ISSUE TITLE
LocalStorage reset when AoT is enabled

### ISSUE THREAD

**Issue by mrdaliri** [zoomsphere/ngx-store#16]
Hi Daniel,

Thanks for forking old angular2-localstorage and creating this useful package.

I just ran into a bug when enabling AoT: My decorated variables get reset when navigating between different routes. (moving to other components) Note that variables defined as Component fields.

For example, look at this snippet: (from package samples)

```
export class MySuperComponent {
  @LocalStorage() public viewCounts: number = 0;
  constructor() {
    this.viewCounts++;
  }
}

export class OtherComponent {}
```
When I visit `MySuperComponent` route, it saves number `1` in local storage (checked through Chrome DevTools), then I go to `OtherComponent` (via `router.navigateByUrl('/other')`), still `1` is shown as `viewCounts` in DevTools, finally when go back to `MySuperComponent` (again with `router.navigateByUrl('/super')`) the value of `viewCounts` is `1`, while it should be `2`, `1+1=2`.

But if I reload page while I'm on `MySuperComponent` (means exactly same route), `viewCounts` increased and saved correctly.

This behavior does not occur when AoT is disabled. (`--no-aot` on Angular-CLI)

**Comment by DanielKucal** [comment]
Hi Mohammad, I think I know what is the problem... You may not like the solution, as it's not perfect, but only possible at this time. The exact problem here is that `ngx-store` uses Angular's lifecycle hook `OnDestroy` to prevent overwriting current value by initial one and the hook is not being fired when your component doesn't have this method defined before Ahead of Time compilation runs. So the best you can do is to implement `OnDestroy` interface, including adding `ngOnDestroy() {}` method - even empty, but must be present in the class you are using decorator on. Hope it solves your problem, thanks for understanding. 
PS: Don't forget to update to `v1.1.7`, it contains small fix for related issue.

**Comment by DanielKucal** [comment]
Hey @mrdaliri, did it solve your problem?

**Comment by DanielKucal** [comment]
**Limited lifecycle classes in AoT compilation** instructions have been added to README.
