### ISSUE TITLE
AoT production build causes isssues with boolean value on local storage.

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/ngx-store#20]
Hi, it's me again :-)

I'm having a weird issue with I'm not 100% sure is related to this library but it might.
The problem is that when I use a boolean value with `@LocalStorage()` the value get overridden every time the component is initialized again - this only happen when using `--prod` flag with angular-cli.
I think this might be new to angular-cli 1.4.4 which I recently updated to but I can't be sure.
The following is the relevant issue in my repository:
https://github.com/IsraelHikingMap/Site/issues/493

No sure I can reproduce it on a plunker since it requires AoT compilation.
Please let me know if you are able to reproduce.

The behavior I'm seeing, as described in the linked issue, is that the value is presented the first time the component shows up, but every time after that the component returns to the default value.

**Comment by DanielKucal** [comment]
Hi @HarelM, is this field declared in a Component or Service? If it is a Service, is it declared in providers for some component?
If the answer for second question is positive, then please try this: https://github.com/zoomsphere/ngx-store/issues/16#issuecomment-322369816

**Comment by HarelM** [comment]
It is declared in a component, I'll try to use ngDestroy and see if it helps...

**Comment by HarelM** [comment]
Thanks for the tip, adding `ngOnDestroy` seems to solve my issue so this is probably a duplicate of #16.

**Comment by DanielKucal** [comment]
Thanks, I have to add this solution to README
