### ISSUE TITLE
Decorators for objects are not working as of 4.4.6?

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/ngx-store#24]
I'm not 100% sure but seems like as of 4.4.6 things have stopped working for properties with decorator for non primitives:
i.e - the following is always reverting to default value...
```
@LocalStorage()
    private center = L.latLng(31.773, 35.12);
```
but the following works:
```
    @LocalStorage()
    private zoom: number = 13;
```
Does this happen only for me?

**Comment by DanielKucal** [comment]
Hi @HarelM, thank you for this report! It wasn't about Angular version... Just seems like the fix for boolean values I applied last time wasn't complete, corrected in `v1.2.3`

**Comment by HarelM** [comment]
Thanks for the superquick response, I'll test tonight if this solves my problem.

**Comment by HarelM** [comment]
Seems like this solve the issue, thanks!
I suggest to start adding tests to avoid such cases in the future :-)

**Comment by DanielKucal** [comment]
Yup, I'm not adding any new features until we have tests ;)
