### ISSUE TITLE
import from 'rxjs/Rx'

### ISSUE THREAD

**Issue by stenatpsc** [zoomsphere/ngx-store#27]
Hi, 

there are some files with
`import { Observable } from 'rxjs/Rx';`
instead of
`import { Observable } from 'rxjs/Observable';`

which causes builds with  --build-optimizer enabled to fail

**Comment by DanielKucal** [comment]
Hi @stenatpsc, thank you for this report. I've seen you have already corrected these import statements in your fork. Would you like to open a pull request?

**Comment by stenatpsc** [comment]
Hi @DanielKucal, thanks for your quick reply. Yes, will open a pull request

**Comment by DanielKucal** [comment]
Resolved by https://github.com/zoomsphere/ngx-store/pull/28
