### ISSUE TITLE
indexOf for array stored in local storage

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/ngx-store#3]
Hi,

I'm not sure if this is a problem with my code or not but I use the following code:

```js
export class Foo {
...
 @LocalStorage()
    private activeOverlayKeys: string[] = [];
..
```
Then I use this array with indexOf method:
```js
this.activeOverlayKeys.indexOf(overlay.key) === -1
```
And for some reason I get and erorr: 
```activeOverlayKeys does not have indexOf method```

I'm not sure if this has to do with the target of my compilation or this library, but it's weird...
I have removed the index of method and converted it to `_.find` using lodash, but it feels like a workaround...
If you have an initial pluker with this library rigged I can try and reproduce...

**Comment by DanielKucal** [comment]
Hi @HarelM, I've just checked it and everything looks fine. Output code was transpilled to ES5. Please make sure you have the latest version of `ngx-store` installed. 
![image](https://user-images.githubusercontent.com/8938562/27500181-979eec52-5867-11e7-8b88-8f3a111eb850.png)

**Comment by HarelM** [comment]
For some reason, when using the latest version and using `ng build -w` I'm getting the following error:
```
ERROR in D:/Github/IsraelHikingMap/Site/IsraelHiking.Web/node_modules/ts-debug/debug.d.ts (3,21): Namespace 'NodeJS' has no exported member 'ConsoleConstructor'.
```
This does not happen when using just `ng build` I can't really explain this, but I can't use the latest version (1.0.4)...
Are you aware of such an issue that was fixed between 0.6.1 (the version I'm using) and the latest version?

**Comment by DanielKucal** [comment]
Can you please try `npm install ts-debug@beta`, then `npm install ngx-store@latest` and compile with the first command? What kind of build it actually is (`nb build -w`)?

**Comment by HarelM** [comment]
Sorry, `ng` not `nb`.
I'll test it later today.

**Comment by DanielKucal** [comment]
Hey @HarelM, have you checked it out? Did `ts-debug@beta` solved the problem?

**Comment by HarelM** [comment]
Haven't got to it yet, sorry, hopefully soon...

**Comment by DanielKucal** [comment]
@HarelM can this issue be closed?

**Comment by HarelM** [comment]
Unfortunately I'm not getting to check it, probably because I have a workaround. I'll reopen if I'll get to it and find out it's problematic.

**Comment by HarelM** [comment]
Latest version seem to have this fixed including ts-debug.
Thanks!
