### ISSUE TITLE
getting localStorage is not defined 

### ISSUE THREAD

**Issue by 8bitreid** [zoomsphere/ngx-store#35]
After implementing this exactly like the examples I get a localStorage is not defined.

**Comment by DanielKucal** [comment]
Hi @8bitreid, `localStorage` should be defined in a web browser. What environment do you refer to?

**Comment by 8bitreid** [comment]
@DanielKucal  I found the issue.  I had an AuthService that used `localStorage`. this worked well.  I attempted to make a route guard that looked at my AuthService and returned a boolean so I could secure up my navigation.  This is what failed.  I was referenced a method that looked at `localStorage` on server side code.  
my issue was with my route guard using a server side class to check for canActivate.
