### ISSUE TITLE
dynamically change prefix?

### ISSUE THREAD

**Issue by bkinsey808** [zoomsphere/ngx-store#40]
Is there a way to dynamically change the prefix? My use case is where multiple users use the same computer. I want to put each user's local storage data under a different prefix.

**Comment by DanielKucal** [comment]
Hi @bkinsey808, the simplest way to do it is to use [builder pattern](https://github.com/zoomsphere/ngx-store/tree/master/src/service#builder-pattern) this way:
```typescript
  this.localStorageService.load('someKey').setPrefix(yourDynamicValue).save({user: 'settings');
```
But I'd rather suggest you to consider using your own prefix while leaving the default one - what I mean is to store the data under keys like `ngx_45_user`, `ngx_83_user` etc.
Or just like we do it in main ZoomSphere project: store all settings in single object, e.g.:
```json
{
  "45": { "timeZone": "+2" },
  "83": { "timeZone": "UTC" }
}
```
Then you can abstract this functionality like shown in the example of builder pattern in the docs.

**Comment by bkinsey808** [comment]
thanks
