### ISSUE TITLE
localStorage is not defined (Angular Universal)

### ISSUE THREAD

**Issue by rreddyNg** [zoomsphere/ngx-store#42]
Hi Dan, when I compile my project with angular universal, I get this error:

`ConfigHelper._webStorageUtility = new__WEBPACK_IMPORTED_MODULE_0__utility_webstorage_utility__["a" /* WebStorageUtility */](localStorage, CONFIG_PREFIX); `

`ReferenceError: localStorage is not defined`

**Comment by DanielKucal** [comment]
Duplicate of https://github.com/zoomsphere/ngx-store/issues/18
