### ISSUE TITLE
when will be updated to compatible with angular v6?

### ISSUE THREAD

**Issue by byunru** [zoomsphere/ngx-store#43]

**Comment by DanielKucal** [comment]
Angular 6 hasn't been even released yet, it's on "release candidate" stage. I think we will update ngx-store after some time Angular 6 is released. Have you already tested it? What is the issue you are experiencing with A6? You can prepare a PR, so it will be compatible much earlier, if you want.

**Comment by byunru** [comment]
Angular 6 has dependency on rxjs v6, and ngx-store broken on rxjs v6

**Comment by tolvaly** [comment]
rxjs changed the import strategy:

[v6.0.0-alpha.1 changelog](https://github.com/ReactiveX/RxJS/compare/5.5.3...v6.0.0-alpha.1)

> * creation functions: All create functions such as of, from, combineLatest and fromEvent should now be imported from rxjs/create.

> * operators: Pipeable operators must now be imported from rxjs like so: import { map, filter, switchMap } from 'rxjs/operators';. No deep imports.

> * deep imports: Can no longer deep import top-level types such as rxjs/Observable, rxjs/Subject, rxjs/ReplaySubject, et al. All imports should be done directly from rxjs, for example: import \{ Observable, Subject \} from 'rxjs';

I suggest to use version numbering used by rxjs in the future release

**Comment by DanielKucal** [comment]
> I suggest to use version numbering used by rxjs in the future release

@tolvaly, what do you mean? Thanks for describing the changes.

**Comment by tolvaly** [comment]
So, if the new version will be compatible with rxjs 6.0.0+ then the released version major number should be equal to the compatible rxjs major version number, so something like 6.x.x. It will help us in version selection for our projects
