### ISSUE TITLE
.save() is not a function

### ISSUE THREAD

**Issue by Mattomanka** [zoomsphere/ngx-store#44]
Hi, 
i saw similar issue. (https://github.com/zoomsphere/ngx-store/issues/9)
But i didn't touch config and it doesn't work.

```
   import { LocalStorage } from 'ngx-store';

  @LocalStorage('idkey') id: any;
  @LocalStorage('ounkey') name: any;

    this.id = data._id;
    this.name = data.name;
    this.id.save();
    this.name.save();

**Comment by DanielKucal** [comment]
Hi @Mattomanka, it seems like you are missing default values:
```typescript
  @LocalStorage('idkey') id: any = {};
  @LocalStorage('ounkey') name: any = {};
```
And it's worth to note that the `.save()` method is added only for objects (including arrays). Simple types just don't need it, they can be saved automatically. So if your `id` and `name` are just strings, numbers or booleans you don't need to invoke this method. Hope I helped.

**Comment by Ralpharoo** [comment]
@DanielKucal Thanks. The approach and method work fine to trigger a save at runtime, however this causes me TSLint errors throughout my project;

> error TS2339: Property 'save' does not exist on type 'object'.

Is there an easy way to resolve this locally?
