### ISSUE TITLE
error TS2420: Class 'NgxStorageEvent' incorrectly implements interface 'StorageEvent'

### ISSUE THREAD

**Issue by npjonath** [zoomsphere/ngx-store#45]
We got few error after installing ngx-store to latest 5.2.10 Angular.
`ERROR in node_modules/ngx-store/src/utility/storage/storage-event.d.ts(1,22): error TS2420: Class 'NgxStorageEvent' incorrectly implements interface 'StorageEvent'.
  Property 'NONE' is missing in type 'NgxStorageEvent'.
`

We have solved this by adding to ngx-store/src/utility/storage/storage-event.d.ts :
`oldValue: any; // remove optional oldValue`
`readonly NONE: any; // add this`

**Comment by DanielKucal** [comment]
You can also downgrade TypeScript version to v2.6 or set `skipLibCheck` to false. This is related to https://github.com/zoomsphere/ngx-store/issues/41

**Comment by npjonath** [comment]
Ok, skipLibCheck flag do the job for us. thanks.
