### ISSUE TITLE
 no exported member 'Observable' in angular 6

### ISSUE THREAD

**Issue by webexpert4rv** [zoomsphere/ngx-store#49]
ERROR in node_modules/ngx-store/src/service/webstorage.service.d.ts(3,10): error TS2305: Module '"/home/user/dee/angular6/admin-template/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-store/src/utility/storage/storage.d.ts(2,10): error TS2305: Module '"/home/user/dee/angular6/admin-template/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ngx-store/src/utility/webstorage.utility.d.ts(3,10): error TS2305: Module '"/home/user/dee/angular6/admin-template/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ngx-store/src/utility/webstorage.utility.d.ts(5,10): error TS2305: Module '"/home/user/dee/angular6/admin-template/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

**Comment by DanielKucal** [comment]
It will be resolved by upgrading to Angular 6 in https://github.com/zoomsphere/ngx-store/pull/47
