### ISSUE TITLE
force save on non-basic types

### ISSUE THREAD

**Issue by essadji** [zoomsphere/ngx-store#56]
basic types are directly bound and are synced without forcing a save.
Apparently this is not the case for arrays.
Forcing the save keeps them synced but I wonder whether it's intended behaviour for non-basic types?
Furthermore, upon saving, I get a warning: 
error TS2339: Property 'save' does not exist on type '{ name: string; }[]'.

Any way to get rid of it (it does work as is, however)

**Comment by DanielKucal** [comment]
Hi @essadji, basic types just don't need a force save. To avoid error TS2339, you need to use `Webstorable` interface (defined here: https://github.com/zoomsphere/ngx-store/blob/master/src/ngx-store.types.ts#L1), e.g.:
```typescript
export class MyClass {
  @LocalStorage() public myVariable: MyType & Webstorable = <any>{};
}
```
or just `any` type (not recommended).
