### ISSUE TITLE
How to handle 'stale' cached objects?

### ISSUE THREAD

**Issue by Moulde** [zoomsphere/ngx-store#59]
How do you guys handle this scenario?

1. A user stores an object of type interface AppInfo with A, B, C properties, in version 1 of the application in LocalStorage.
2. Me, the developer adds a new property D, to the AppInfo interface, with a value that is used in the application, and pushes version 2 of the application.
3. The user loads version 2 of the application, which loads the old AppInfo object without property D from localstorage.
4. Exception, as the AppInfo is now missing the D property that is used in the application.

I'm not sure the best place to solve this is even in this package, it may very well be completely out of scope of the package.

I attempted to solve it by changing the AppInfo to a class instead of an interface, and give the properties default values, but that didn't work. Then i tried assigning the property to a casted instance of itself.
    
    this.appInfo = <AppInfo>this.appInfo;

But no cigar, the default value was not added by casting the object.
The solution I ended up going with, was just to check if the value was undefined, and if it was, use the default value, but this forces me to explicitly check each property, so i'd prefer to just set the default value in the class, and have it automatically use that, and i bet it's possible, with some fancy JS (or TS), that I don't know.

What do you guys think?
(@DanielKucal if this is the wrong place for this discussion, feel free to delete)

**Comment by DanielKucal** [comment]
You could use the builder pattern and its [`.setDefaultValue()`](https://github.com/zoomsphere/ngx-store/blob/9c41736eaa14546928df2a172c4e7d3917f79efa/src/service/resource.ts#L112) method, it'd give you the cleanest code.
