### ISSUE TITLE
ngx-store doesn't installed in node_modules

### ISSUE THREAD

**Issue by webspecialist** [zoomsphere/ngx-store#60]
I am using Angular 6 and I get the below message:

./node_modules/ngx-store/src/service/local-storage.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'F:\angular\mySite18\node_modules\ngx-store\src\service'

I have tried both installations with npm 
npm i ngx-store --save or npm i ngx-store@RC

In my package.json 
I have "ngx-store": "^1.4.3"

I tried to find in node_modules ngx-store folder but there isn't there. What can I do?

**Comment by Moulde** [comment]
v2.0.0 - support for Angular 6 (RxJS v6)

You are using a version that isn't built for angular 6

**Comment by webspecialist** [comment]
How to install v2.0.0?

**Comment by Moulde** [comment]
Just change the version in the package.json file and do npm install again.

**Comment by DanielKucal** [comment]
`npm i ngx-store@latest` should do the job.
