### ISSUE TITLE
ts-debug 1.3 is not compatible with Angular 6

### ISSUE THREAD

**Issue by micha2el** [zoomsphere/ngx-store#71]
Hi,

using your ngx-store installs ts-debug ^1.1.2 which currently installs ts-debug 1.3.0 which needs typescript 3.0 which is only supported in Angular 7. This makes a today compilation not work despite working yesterday (before release). Error is:

ERROR in node_modules/ts-debug/debug.d.ts(1,22): error TS2420: Class 'Debugger' incorrectly implements interface 'Console'.
  Property 'msIsIndependentlyComposed' is missing in type 'Debugger'.

Can you fix this?

Thanks :)

**Comment by tonyholt** [comment]
I second this.  Can the previous version of this library use 1.2.0 without the "^"?  That would be a good measure to ensure that ngx-store 2.0.0 will continue to work with Angular 6

**Comment by tonyholt** [comment]
@micha2el, a member of my team figured out a workaround.  Add the following to your "dependencies" in your application's package.json (NOT devDependencies):

"ts-debug": "1.2.0"

This solved it for us.

**Comment by micha2el** [comment]
@tonyholt Thx. This works for me as well.

**Comment by tonyholt** [comment]
Great... I still hope they can lock down that ts-debug reference in version 2.0.0 so that people can downgrade to 2.0.0 gracefully

**Comment by DanielKucal** [comment]
I cannot push lower version to npm, so you have to use ngx-store v2.0.0 or `npm i ts-debug@1.2.0 --save` (like @tonyholt mentioned up) for Angular versions older than 7.
