### ISSUE TITLE
4 fundamental methods for simple usage of ngx-store

### ISSUE THREAD

**Issue by MichalMoravik** [zoomsphere/ngx-store#72]
I would like to use ngx-store for simple functionalities - save, display, update (real time) and delete (real time). 

My case: I have a simple web shop only for educational purposes. User should be able to add objects to the session storage (add to cart) then the checkout page should display cart of objects and user should be able to add or remove quantity of product (real time update) and should be able to remove product from the cart (real time deletion). 

What I did so far is saving objects to the session storage in product-list page declaring:
`@SessionStorage({key: 'cart'}) objectArray: Array<Object> = [];`
and then pushing the object to the array:
`this.objectArray.push(object);`

I was also successful to display data from the session storage again by declaring:
`@SessionStorage({key: 'cart'}) objectArray: Array<Object> = []; `
this time in different component typescript file and then I was able to display data using ngFor in html file. 
`<div *ngFor="let object of objectArray"></div>`

I am not sure if I did it correctly as I am beginner (student) and we have just started using Angular. But these two methods work. Therefore I would like to ask you for help with the other two methods. Method for saving updated product (its updates quantity field) to the session storage in real time after I click on + or - quantity button. And method for deletion of the object from the session storage in real time.

I will be thankful for any kind of help. Thank you.

**Comment by DanielKucal** [comment]
> Method for saving updated product (its updates quantity field) to the session storage in real time after I click on + or - quantity button.

Can you post here your form template?

> And method for deletion of the object from the session storage in real time.

Simply do `this.objectArray = [];` (or `null` / `undefined` if you wish).

**Comment by MichalMoravik** [comment]
Thank you! @DanielKucal 
here is the OrderLine object model. And in the session storage I have an array of these object (objectArray). 
`export class OrderLine {
  mealId?: number;
  meal?: Meal;
  orderId: number;
  quantity: number;
  priceWhenBought: number;
}`

then here is the html piece of code responsible for displaying these OrderLines from the session storage array (in png form because I wasn't able to put it as a code)
<img width="771" alt="screen shot 2018-12-13 at 03 53 54" src="https://user-images.githubusercontent.com/32333157/49912551-c9d63200-fe8a-11e8-8344-953b3c95d992.png">
For testing purposes I added input where you can specify quantity and you will see the change on the particular object's quantity immediately. But I will probably change it to the button + and button -  later.

And this input points on method changeOrderLineMeal() which look like this:
<img width="426" alt="screen shot 2018-12-13 at 03 59 31" src="https://user-images.githubusercontent.com/32333157/49912766-85976180-fe8b-11e8-9330-b2dbdeb7e135.png">

where I was only able to get the index of object in the array which has changed quantity and then replace it in the array with the updated object with the new quantity. I think the code for updating session storage should be here.
The problem is, that this is happening only locally. I would like to update it in the session storage too. Do you think it could be maybe possible to just push the updated array to the session storage? I couldn't figured out any solution.

Thank you very much for you help.

**Comment by DanielKucal** [comment]
And `(<any>this.orderLineMealsInCart).save()` at the end of method `changeOrderLineMeal()` doesn't work?

**Comment by MichalMoravik** [comment]
Thank you! I finished it. 
![image](https://user-images.githubusercontent.com/32333157/49935821-6839b600-fed2-11e8-9c88-90eda032d749.png)

changeOrderLineMeal() updates, deleteOrderLineMealFromCart() removes object from the array, removeEverythingFromCart(), well, removes everything and leaves empty array so customer is able to put items to the cart again. 

Thank you for your help.
