### ISSUE TITLE
First time writing to @LocalStorage() doesn't work?

### ISSUE THREAD

**Issue by Olindholm** [zoomsphere/ngx-store#73]
Hey, I'm quite new to Angular so forgive me if this is all on my part. However, let me explain.

I have a class Auth for storing a login token provided from the server whenever correct username and passwords are provided. I had this weird behavior that after initially loading the page, on the first login or logout. I need to press the button twice, in order for something to actually happen. After that, it works everytime.

Here's my class
```
import { Injectable } from '@angular/core';

import { LocalStorage } from 'ngx-store';

@Injectable()
export class Auth {

	@LocalStorage() token: string;

	public isLoggedIn() {
		return (this.token) ? true : false;
	}

	public login(token: string) {
		this.token = token;

		console.log("You're logged in!");
		console.log(this.token);
	}

	public logout() {
		this.token = '';

		console.log("You're logged out!");
		console.log(this.token);
	}

}
```

So my debugging has come to find, that ngx-store is the issue. removing ```@LocalStorage()``` will fix the issue. Also duplicating the assignments, i.e. ```this.token = token;```or ```this.token = '';``` will also resolve the issue.

For some reason it only seems the very first assignment to the variable doesn't seem to be respected.

**Comment by dirkluijk** [comment]
I have the same issue. Assigning a default value solves this, but raises another problem when I use it on a component which is instantiated multiple times.

**Comment by DanielKucal** [comment]
@Wiggyboy, you have to assign a default value, as described in README.
@dirkluijk, in this case, I'd place such a variable in a service.
