### ISSUE TITLE
How to set a secure cookie?

### ISSUE THREAD

**Issue by ghost** [zoomsphere/ngx-store#78]
I can't find a way to set a secure cookie, is that even possible with ngx-store?

**Comment by lukengda** [comment]
Do you see the cookie available if you `console.log(document.cookie)`? Is the `http-only` flag set for the cookie in question?

**Comment by DanielKucal** [comment]
"Secure cookies are a type of HTTP cookie" - Wikipedia.
It means that a secure cookie can be set by a web server only, hence it's impossible from JavaScript level.
