### ISSUE TITLE
Persisting a mutable object with a particuar class

### ISSUE THREAD

**Issue by feliu** [zoomsphere/ngx-store#8]
First of all thanks for your great work!

I want to be able to persist objects with these shape:

export class LoginModel {
  constructor(
    public email: string,
    public pass: string
  ) {  }
}
The only way that I found to persist mutable object is assigning a type any and later using the .save() method. But I want to be able to use my own types. Is that possible?

**Comment by DanielKucal** [comment]
Hi @feliu, thanks, you can give this project a star to show your support :) Please try this:
```
export class LoginModel implements Webstorable {
    constructor(
        public email: string,
        public pass: string
    ) { }
    public save() {}
}
```

**Comment by DanielKucal** [comment]
Hey @feliu, did that solve your problem and can we close this issue?

**Comment by DanielKucal** [comment]
Closing as outdated and probably solved.
