### ISSUE TITLE
Intermittently does a JSON.stringify on this.sessionStorageService.get()

### ISSUE THREAD

**Issue by BBlackwo** [zoomsphere/ngx-store#80]
For some reason when I am reading from session storage on an already stringified object `"{"foo":"bar"}"`, it will do *another* `JSON.stringify()` and my session storage becomes double stringified.

```js
this.sessionStorageService.get('myKey');
```

Then my session storage becomes double stringified

```js
sessionStorage.getItem('myKey'); // "{\"foo\":\"bar\"}"
```

It's hard to reproduce as it seems to happen intermittently 🤷‍♂

**Comment by DanielKucal** [comment]
It's simply because you used native `sessionStorage` instead of ngx-store's `sessionStorageService`. Native `sessionStorage` doesn't parse the data, so you get what was saved by ngx-store and it's a stringified data.
