### ISSUE TITLE
Not compatible with Angular 9.1

### ISSUE THREAD

**Issue by patrickrioux** [zoomsphere/ngx-store#86]
Hi,

After upgrading to Angular 9.1, the compile get this error:

ERROR in node_modules/ngx-store/src/ngx-store.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-store) which declares WebStorageModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Can someone fix this?

**Comment by jan-moxter** [comment]
see #81 . Its an ivy issue that requires to change the library to use angular layout

**Comment by ghost** [comment]
Will this happen any time soon? Or is this lib obsolete?

**Comment by jan-moxter** [comment]
See #81

**Comment by DanielKucal** [comment]
Latest version supports Angular 9+ and IVY
