### ISSUE TITLE
.save() is not a function

### ISSUE THREAD

**Issue by craftpip** [zoomsphere/ngx-store#9]
Hello there!,

i tried this 
```js
export class MySuperComponent {
  @LocalStorage() public someObject: any = { c: 3 };
   
  constructor() {
    this.someObject.a = 1;
    this.someObject.save();
   }
}```
and got the error save is not a function.

Thanks.

EDIT:
I'm using angular4

**Comment by craftpip** [comment]
okay, i got this solved by setting 
`mutateObjects: true`, in the config,
please add this to your docs. 
👍

**Comment by DanielKucal** [comment]
Hi @craftpip, thanks for your interest in this project! `mutateObjects` should be set to `true` by default, wasn't it for you? I think it's described properly in [README#Configuration](https://github.com/zoomsphere/ngx-store#configuration) section, how would you improve it?

**Comment by craftpip** [comment]
Yea, sorry about that, i completely missed it. 
Keep up the good work! 💯

**Comment by craftpip** [comment]
However, can you add a NOTE below the 'Force save changes' example. That save function is only available when mutate is true. 
I think most of the users jump straight to the code examples.

**Comment by DanielKucal** [comment]
So it wasn't enabled by default for you? It would be a bug, because `mutateObjects: true` in [DefaultConfig](https://github.com/zoomsphere/ngx-store/blob/master/src/config/config.ts#L13)

**Comment by craftpip** [comment]
it was a default option, and then saw the options and decided not to mutate objects.

**Comment by DanielKucal** [comment]
Okay, thanks for this information. I think we can close this issue now

**Comment by DanielKucal** [comment]
Okay, thanks for this information. I think we can close this issue now

**Comment by DanielKucal** [comment]
Update: now you can set `mutate` property in decorator for single object, e.g.:
```typescript
@LocalStorage({ mutate: false, key: 'user-data' }) notMutated  = {};
```
