### ISSUE TITLE
'oldValue' in type 'NgxStorageEvent<T>' is not assignable to the same property in base type 'StorageEvent'

### ISSUE THREAD

**Issue by AndreMantas** [zoomsphere/ngx-store#97]
Not sure if this is already being tracked, but got this error during build after installing latest version (`"ngx-store": "^3.0.0"`)
```
ERROR in node_modules/ngx-store/lib/utility/storage/storage-event.d.ts:6:5 - error TS2416: Property 'oldValue' in type 'NgxStorageEvent<T>' is not assignable to the same property in base type 'StorageEvent'.
  Type 'T' is not assignable to type 'string'.
```
For now i'm setting `"skipLibCheck": true,` but thats not ideal.

**Comment by VladVKozlov** [comment]
I'm getting that too, on Angular 12 "typescript": "4.2.4". I'm thinking of extracting this library to my project and use     
`// @ts-ignore `
on these fields, but that definitely needs to be fixed in future

**Comment by thekendalmiller** [comment]
Another me too. Could we a get a 3.0.2 release that fixes this?
Thanks
