### ISSUE TITLE
Missing ts-debug in dependencies

### ISSUE THREAD

**Issue by dhruv1297** [zoomsphere/ngx-store#99]
I was using the ngx-store in my angular 11 app, and I noticed that ngx-store internally uses ts-debug library. Now this is present in the peerDependencies of your package.json, but ts-debug is absent in the dependencies part itself. Please add the library in dependencies so that this issue could be resolved.
![image](https://user-images.githubusercontent.com/17988167/132646216-1b7a3ae6-e6a0-4773-89bd-6962e081cf42.png)
![image](https://user-images.githubusercontent.com/17988167/132646269-0d4cca18-fd1f-4999-9d2a-594c84d1300f.png)

**Comment by DanielKucal** [comment]
Strange it wasn't installed by ng-packagr, added to deps for now.
Thanks for your report.
